site:
  name: "Rx4Miracles"
  domain: "rx4miracles.org"
  description: "Free prescription savings card program supporting Children's Miracle Network Hospitals"
branding:
  primary_color: "#0066CC"
  greeting: "Hey! I'm here to help you save on prescriptions with Rx4Miracles. How can I assist you today?"
ai:
  model: "gpt-4o-mini"
  temperature: 0.4
  max_tokens: 500
  system_prompt: |
    You are a helpful, compassionate assistant for Rx4Miracles, a FREE prescription savings card program.
    PERSONALITY & TONE:
    - Warm, patient, and encouraging (healthcare costs are stressful for many people)
    - Clear and jargon-free language
    - Enthusiastic about helping people save money AND support children's hospitals
    - Never judgmental about financial situations
    - Emphasize "free" and "easy to use"
    YOUR ROLE:
    - Answer questions using the information provided to you
    - Be as concise as possible. Don't be too wordy.
    - Help people understand how to get and use the prescription savings card
    - Keep responses concise and helpful
    BOUNDARIES - What You CANNOT Do:
    - Do NOT provide specific drug pricing (prices vary by pharmacy and medication)
    - Do NOT provide medical advice or recommend medications
    - Do NOT make guarantees about exact savings percentages
    - Do NOT share patient information or process applications
    WHEN TO ESCALATE:
    For technical website issues, specific medication pricing, pharmacy problems, or partnership inquiries, direct users to contact the team at 833-511-9500.
    Use the relevant information provided below to answer user questions accurately and helpfully.
business:
  contact:
    phone: "833-511-9500P"  # TODO: Update with actual number
    hours: 24/7
    website: "https://rx4miracles.org"
  quick_links:
    how_it_works: "https://rx4miracles.org/how-it-works"
    participating_pharmacies: "https://rx4miracles.org/pharmacies"
    partner_organizations: "https://rx4miracles.org/partners"
    supported_hospitals: "https://rx4miracles.org/hospitals"
  escalation:
    keywords:
      - "speak to someone"
      - "human"
      - "representative"
      - "complaint"
      - "urgent"
      - "technical issue"
      - "website problem"
      - "pharmacy won't accept"
    message: "I'd be happy to connect you with our team. You can reach us at [PHONE] or email [EMAIL], and someone will help you right away."
charitable_mission:
  partner: "Children's Miracle Network Hospitals®"
  hospitals_supported: 170+
  description: "Rx4Miracles donates funds to Children's Miracle Network Hospitals® to support pediatric healthcare"
  # Major hospital partners (sample - full list of 170+ available)
  featured_hospitals:
    - "Boston Children's Hospital"
    - "Children's Healthcare of Atlanta"
    - "Children's Hospital of Philadelphia"
    - "Cincinnati Children's"
    - "Texas Children's Hospital"
    - "Seattle Children's Hospital"
    - "Children's Hospital Los Angeles"
    - "Nationwide Children's Hospital"
    - "Phoenix Children's Hospital"
    - "Riley Hospital for Children"
pharmacy_partners:
  total_count: 68000+
  major_chains:
    - "CVS Pharmacy"
    - "Walmart Pharmacy"
    - "Walgreens"
    - "Kroger"
    - "Publix"
    - "Target Pharmacy"
    - "Rite Aid"
    - "Safeway"
    - "Albertsons"
    - "Fred Meyer"
    - "Vons"
    - "Tom Thumb"
    - "Randalls"
    - "Harris Teeter"
    - "Giant"
    - "Stop & Shop"
  independent_pharmacies: true
  pharmacy_locator: "https://rx4miracles.org/pharmacies"
medical_association_partners:
  - "Medical Association of Georgia"
  - "Hawaii Medical Association"
  - "Iowa Medical Society"
  - "Illinois State Medical Society"
  - "Massachusetts Medical Society"
  - "MedChi (Maryland)"
  - "Tennessee Medical Association"
  - "Medical Society of Virginia"
program_details:
  cost: "Free (no premiums or fees)"
  enrollment_required: false
  coverage:
    medication_count: "~20,000 FDA-approved medications"
    types: "Brand name and generic prescriptions"
    savings: "Up to 80% off cash prices"
  eligibility:
    requirements: "None - open to everyone"
    no_restrictions:
      - "No income limits"
      - "No age restrictions"
      - "No pre-existing condition exclusions"
      - "No deductibles"
      - "No waiting periods"
      - "No membership fees"
  ideal_for:
    - "People without prescription drug coverage"
    - "People with high deductibles"
    - "People with high co-pays"
    - "People facing formulary limitations"
    - "People with gaps in coverage"
    - "Anyone paying cash out-of-pocket for medications"